server.port: 8080
spring.application.name: gateway-service
spring.cloud.gateway:
  mvc.routes:
    - id: author-service
      #uri: http://localhost:8060
      uri: lb://author-service/api/v1
      predicates:
        - Path=/api/v1/author/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
