server.port: 8080
spring.application.name: gateway-service
spring.cloud.gateway:
  mvc.routes:
    - id: article-service
      uri: http://localhost:2062
      #uri: lb://article-service
      predicates:
        - Path=/api/v1/article/**
    - id: country-service
      uri: http://localhost:2063
      #uri: lb://article-service
      predicates:
        - Path=/api/v1/country/**
    - id: price-service
      uri: http://localhost:2061
      #uri: lb://article-service
      predicates:
        - Path=/api/v1/price/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
