server.port: 8080
spring:
  application.name: gateway-service

spring.cloud.gateway:
  mvc.routes:
    - id: article-service
      #uri: http://localhost:2062
      uri: lb://article-service
      predicates:
        - Path=/api/v1/article/**
        #- before=2024-05-02T19:37:00.000-05:00
        - Cookie=chocolate, 70
      filters:
        - RemoveRequestHeader=Cookie

    - id: country-service
      #uri: http://localhost:2063
      uri: lb://country-service
      predicates:
        - Path=/api/v1/country/**
        - between=2024-01-19T02:45:00.000-05:00, 2024-02-17T19:31:00.000-05:00
        - cookie=auth,java
      filters:
        - RemoveRequestHeader=X-My-Header
        - addResponseHeader= X-My-Header, 17012024
        - RemoveResponseHeader=X-My-Untrusted-Header
    - id: price-service
      #uri: http://localhost:2061
      uri: lb://price-service
      predicates:
        - Path=/api/v1/price/**
        - before=2024-01-02T07:45:00.000-05:00
        - Header= x-My-Header, Examen2024

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
